name: Run Maven TestNG Automation (Scheduled)

on:
  schedule:
    - cron: '*/3 * * * *'     # Runs every 3 minutes
  workflow_dispatch:          # Allows manual trigger

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Run Maven Tests
        run: |
          cd Project
          mvn clean test
