name: Run TestNG Automation (Scheduled)

on:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin' # Eclipse Temurin (OpenJDK)

      - name: Verify Java version
        run: java -version

      - name: Run Maven TestNG Tests
        run: mvn clean tes
